version: "3.7"

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=notes_project
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
  web:
    build: .
    command: python notes_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
