version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "sh ./shell/entrypoint.dev.sh && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/notes_project
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.dev
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    env_file:
      - ./env/.env.db
    volumes:
      - dbdata_volume:/var/lib/mysql

volumes:
  dbdata_volume: