version: "3.7"

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - /static:/static
      - ./media:/media
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "sh entrypoint.prod.sh && gunicorn --bind 0.0.0.0:8000 settings.wsgi:application"
    volumes:
      - /static:/static
      - ./media:/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    env_file:
      - ./.env.prod.db
    volumes:
      - dbdata_volume:/var/lib/mysql

volumes:
  dbdata_volume: