version: "3.7"

services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - /static:/static
      - ./media:/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "sh ./shell/entrypoint.prod.sh && gunicorn --bind 0.0.0.0:8000 settings.wsgi:application"
    volumes:
      - /static:/static
      - ./media:/media
    expose:
      - 8000
    env_file:
      - ./env/.env.prod
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    expose:
      - 3306
    env_file:
      - ./env/.env.db
    volumes:
      - ../db/mysql/:/var/lib/mysql
      - ./mysql/my.cnf:/etc/my.cnf
