# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-browsers
        environment:
          - DATABASE_URL: mysql://root@localhost:3306/circle_test?sslmode=disable
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_DATABASE: notes_project
          - MYSQL_USER: root
          - MYSQL_PASSWORD: root
          - MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app