# Generated by Django 2.2.5 on 2019-09-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesbetween20190930and20191006',
            old_name='test',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='notesbetween20190930and20191006',
            name='images',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
