# Generated by Django 2.2.5 on 2019-09-30 14:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190930_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='noted_tables',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=16), max_length=901, size=52),
        ),
    ]
