# Generated by Django 2.2.5 on 2019-09-30 15:16

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190930_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='noted_tables',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=16, null=True), max_length=901, size=52),
        ),
        migrations.AlterField(
            model_name='notesbetween20190930and20191006',
            name='commented_users_id',
            field=django_mysql.models.ListCharField(models.IntegerField(), blank=True, max_length=100, size=None),
        ),
    ]
