# Generated by Django 2.2.5 on 2019-10-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20190930_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesbetween20190930and20191006',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notesbetween20190930and20191006',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
