# Generated by Django 2.2.5 on 2019-10-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20191002_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.ImageField(blank=True, default='icons/iconfinder_profle_1055000.png', upload_to='icons'),
        ),
    ]
