# Generated by Django 2.2.5 on 2019-10-03 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20191002_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(blank=True, default='', upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='noted_num',
        ),
        migrations.RemoveField(
            model_name='account',
            name='noted_tables',
        ),
        migrations.DeleteModel(
            name='NotesBetween20190930and20191006',
        ),
        migrations.AddField(
            model_name='notes',
            name='noted_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
