# Generated by Django 2.2.5 on 2019-10-03 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20191003_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='noted_user_id',
            new_name='author',
        ),
    ]
