# Generated by Django 2.2.5 on 2019-10-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_auto_20191003_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_id',
            new_name='follow',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
