# Generated by Django 2.2.6 on 2019-10-31 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20191003_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created_at']},
        ),
    ]
